### PR TITLE
Feat: Moved methods out of Message to subclasses

### PR DESCRIPTION
**Pull request by Filipjansson95**
I changed a few parameters from private to protected to make them available for the subclasses. Should we perhaps create an own package for all Message classes?

When reviewing this PR look for additional methods to move from the Message class (if you find any). Note that parts of the Project are still broken.

### CODE REVIEW

**Comment by jacobhal** [comment]
I think the most trivial cases are properly split into respective class. 

Some functions are only part of either the Get70 or Put70 classes, which seems to handle client communication with the server for displaying and putting entries in a Region but I am not sure if they are used by clients only.

For instance, the following function is used in Get70 only:
addPartInAnyForm(Object o, boolean isObject) (uncertain about this one and some others which are used in the Get70 class)

Merging the trivial functions first might be a good idea though.

**Comment by Filipjansson95** [comment]
I was hesitant about moving functions regarding Part management due to the email we recived from the creator of the Issue. Email :
"Hi Alexander,We want this refactor as a step toward separating client & server code.This is a tricky refactor because the code for client and server is intermingled in the geode-core module.Message has Part management code, code for serializing/deserializing Parts and send/receive code.  Much of this code is accessed by both clients and servers but there are other methods that are only accessed by client or server, not both.  This makes the class confusing to work with.
You can tell which methods are accessed by Servers by looking for users of the method.  Anything in the Command classes, ServerConnection, CacheClientProxy, CacheClientNotifier are server-side.  Anything in client "pool" classes (ConnectionImpl, CacheClientUpdater, ClientQueueManager, OpExecutorImpl, client "Op" classes like PutOp are client-side.It would also be nice to move the buffer management code out of ServerConnection and move it to a new class.  Client-side code uses these buffer methods & I don't think they should reference ServerConnection.You can add new tests to MessageJUnitTest if your refactoring extends to modifying the methods of Message in order to make sure nothing is broken.  I see it only has 32% code coverage so you would need to add new tests if you're going to refactor any of the methods in Message as opposed to just moving them around." 

What function other than AddPartInAnyFrom() did you find?

**Comment by jacobhal** [comment]
I see, since the functions that you moved are more straightforward to refactor I suggest we merge them first and get everything to compile before taking on the other functions.
Other functions that I found were:
**addStringPart(String str, boolean enableCaching)**: used mainly in ClientUpdateMessageImpl a
and has a cache flag, so I assume this is used by client-side only
**addObjPart(Object o, boolean zipValues)**: used mainly in BaseCommand which seem to be for server-side as mentioned in the email
**addObjPartNoCopying(Object o)**: used similarly to the function above, so I think this one is for the server as well

**Comment by Filipjansson95** [comment]
Ok, I'm merging these changes

**Pull request merged**
